fix expected k8s service account secret type
pomerium/ingress-controller pull request #361
Opened 2022-09-08 21:36 UTC by wasaga

## Summary

We expected an Opaque secret type for the kubernetes service account defined via Ingress annotation 
`kubernetes_service_account_token_secret`. As service accounts are normally created automatically via `ServiceAccount`, they have 
`kubernetes.io/service-account-token` type instead. 

## Related issues

Fixes #335

## Checklist

- [x] reference any related issues
- [ ] updated docs
- [x] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

2022-09-08 21:43 UTC, calebdoxsey requested changes

2022-09-08 21:43 UTC, calebdoxsey commented on config/crd/bases/ingress.pomerium.io_pomerium.yaml
> +                    description: refreshDirectory specifis
find & replace mess up?

2022-09-08 21:43 UTC, calebdoxsey commented on deployment.yaml
> +                    description: refreshDirectory specifis
also here

2022-09-09 15:06 UTC, wasaga commented
I should add `generate` and `manifests` to lint action (in a separate PR). This particular comment change was in the much older PR.

2022-09-09 15:09 UTC, calebdoxsey approved these changes

2022-09-09 16:00 UTC, merged